Bookmark position setting
AlexanderOtavka/clean-tab pull request #25
Opened 2017-11-16 17:47 UTC by VinceWilkie

Adding bookmark position setting + styles, updating tooltips to adjust to bookmark position

2017-11-16 17:48 UTC, VinceWilkie commented
#23

2017-11-16 18:46 UTC, AlexanderOtavka commented
Thanks!  This is some good stuff.  I'll get back to you in a day or two once I have tested this.

2017-11-17 18:30 UTC, VinceWilkie commented
Fixed an issue where the `#main-toolbar` was hidden behind the bookmarks when it was set to left position and always show mode 😄

2017-11-19 02:44 UTC, AlexanderOtavka commented
After some testing, it looks like there is a bug when drawer style is "Show when hovered" and "Small" is checked. The info box and header get stuck on the right instead of centered. I think it's an issue with `--main-left-margin` being unset for that case.

2017-11-19 02:57 UTC, AlexanderOtavka requested changes
Overall, this is fantastic.  I would just like to see a few changes to hopefully eliminate current and future bugs.  Thanks for wading through this rather messy codebase!

2017-11-19 02:57 UTC, AlexanderOtavka commented on elements/x-tooltip/x-tooltip.js
> +        x = this._x + 54;
This `54` seems like a bit of a magic number.  Could you instead of write it in terms of `elementClientRect.width` and the `TOOLTIP_X_OFFSET`?

2017-11-19 02:57 UTC, AlexanderOtavka commented on elements/x-tooltip/x-tooltip.js
> +      let x = this._x - (tooltipClientRect.width - 10);
I think it's time this `10` becomes a named constant `TOOLTIP_X_OFFSET`.  It was already kind of mysterious, and now we are using it in two places (the `54` uses it implicitly)

2017-11-19 02:57 UTC, AlexanderOtavka commented on styles/newtab.css
> +  --main-left-margin: var(--drawer-width);
This needs a default in the `:root` rule.  It should probably be 0.

2017-11-20 16:10 UTC, VinceWilkie commented
Made some changes! Take a look 😃

2017-11-20 17:12 UTC, AlexanderOtavka approved these changes

2017-11-20 17:13 UTC, AlexanderOtavka commented
Thank you!  I'll push out a new version shortly.

2017-11-20 17:13 UTC, merged